ajax/urls.py
from django.contrib import admin
from django.urls import path, include
from items.views import main
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name="main"),
    path('accounts/', include('allauth.urls')),
    path('items/', include('items.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from . import views

app_name="items"
urlpatterns = [
    path('', views.main, name="main"),
    path('new/', views.new, name="new"),
    path('create/', views.create, name="create"),
    path('show/<int:post_id>/', views.show, name="show"),
    path('delete/<int:post_id>/', views.delete, name="delete"),
    path('like_toggle/<int:post_id>/', views.like_toggle, name="like_toggle"),
    path('dislike_toggle/<int:post_id>/', views.dislike_toggle, name="dislike_toggle"),
    path('create_comment/<int:post_id>/', views.create_comment, name="create_comment"),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name="delete_comment"),
]

items/models.py
from django.db import models
from users.models import User

class Post(models.Model):
    title = models.CharField(max_length=50, null=False)
    content = models.TextField()
    view_count = models.IntegerField(default = 0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='images/', null=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    like_user_set = models.ManyToManyField(User, blank=True, related_name='likes_user_set',through='Like')
    dislike_user_set = models.ManyToManyField(User, blank=True, related_name='dislikes_user_set',through='Dislike')

    @property
    def like_count(self):
        return self.like_user_set.count()

    @property
    def dislike_count(self):
        return self.dislike_user_set.count()
        
class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    writer = models.ForeignKey(User, on_delete=models.CASCADE,null=True)


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together =(('user', 'post'))

#싫어요 모델
class Dislike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (('user', 'post'))

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    followings = models.ManyToManyField("self", related_name = "followers", symmetrical=False)
    image = models.ImageField(upload_to="profile_img/", null=True, blank=True)
    info = models.TextField(null=True, blank=True)

items/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import *
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import HttpResponse
import json
from django.template.loader import render_to_string

def main(request):
    items = Post.objects.all()
    return render(request, 'items/home.html', {'items':items})

def new(request):
    return render(request, 'items/new.html')

def create(request):
    if request.method=="POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        user = request.user
        Post.objects.create(title=title, content=content, image=image,user=user)
    return redirect('main')

def show(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.view_count = post.view_count+1
    post.save()
    user = request.user
    context = {
    'post':post,
    'user':user,
    'comments': post.comments.all().order_by('-created_at')
    }
    return render(request, 'items/show.html', context)


#삭제하기
def delete(request,post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.delete()
    return redirect('main')

@login_required
@require_POST
def like_toggle(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_like, post_like_created = Like.objects.get_or_create(user=request.user, post=post)
    # (object, created)

    if not post_like_created:
        post_like.delete()
        result = "like_cancel"
    else:
        result = "like"
    
    context = {
        "like_count":post.like_count,
        "result":result
    }

    return HttpResponse(json.dumps(context), content_type="application/json")

@login_required
@require_POST
def dislike_toggle(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_dislike, post_dislike_created = Dislike.objects.get_or_create(user=request.user, post=post)
    # (object, created)

    if not post_dislike_created:
        post_dislike.delete()
        result = "dislike_cancel"
    else:
        result = "dislike"
    
    context = {
        "dislike_count":post.dislike_count,
        "result":result
    }

    return HttpResponse(json.dumps(context), content_type="application/json")

@login_required
@require_POST
def create_comment(request, post_id):
    user = request.user
    post = get_object_or_404(Post, pk=post_id)
    content = request.POST.get('content')
    comment = Comment.objects.create(writer=user, post=post, content=content)
    rendered = render_to_string('comments/_comment.html', { 'comment': comment, 'user': request.user})
    context = {
        'comment' : rendered
    }
    return HttpResponse(json.dumps(context), content_type="application/json")

def delete_comment(request, comment_id):
    user = request.user
    comment = get_object_or_404(Comment, pk=comment_id)
    rendered = render_to_string('comments/_comment.html', { 'comment' : comment, 'user':request.user})
    comment.delete()
    context={
        'comment' : rendered
    }
    return HttpResponse(json.dumps(context), content_type="application/json")

users/views.py
from django.shortcuts import render

# Create your views here.

ajax/templates/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="{% url 'main' %}">Ajax Practice</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'main' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#">{{ request.user }}님</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'items:new' %}">새글 쓰기</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}">로그아웃</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_login' %}">로그인</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">회원가입</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

ajax/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    {% block css %}
    {% endblock %}

    <title>Ajax Practice</title>
  </head>
  <body>
    
    {% include '_navbar.html' %}

    {% block content %}
    {% endblock content %}
         
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

items/templates/comments/_comment.html
<li class="list-group-item" id="comment-{{ comment.pk }}">
    <p>
        <b>{{ comment.writer.username }}</b>
        {% if user == comment.writer %}
            <a href="#" class="right comment-delete-button" id="comment-delete-{{ comment.pk }}" data-comment-id="{{ comment.pk }}">삭제</a>
        {% endif %}
    </p>
    <p>{{ comment.content }}</p>
</li>

items/templates/comments/items/show.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1><상세보기 페이지></h1>
    <br>
    <h3>글 제목 : {{ post.title }} </h3><br>
    <h3>글 내용 : {{ post.content }} </h3><br>
    <h3>작성 시각 : {{ post.created_at }} </h3><br>
    <h4>조회 수: {{ post.view_count }} </h4><br>

    {% if post.user %}
        <h3> 작성자 : {{ post.user }}</h3>
    {% else %}
        <h3> 작성자 : 알수 없음</h3>
    {% endif %}

    {% if post.image %}
        <img src="{{ post.image.url }}" width="500px" height="500px">
    {% endif %}
    <br>

    {% if post.user == user %}
        <a href="{% url 'items:delete' post.pk %}"> 삭제하기 </a>
    {% endif %}
    <form action="#" method="POST" style="margin-top: 50px;" class="create-comment-form">
        {% csrf_token %}
        <div class="form-group">
            <textarea class="form-control" name="content" id="comment-input-{{ post.pk }}" placeholder="댓글 작성..."></textarea>
        </div>
        <button type="submit" class="btn btn-primary comment-submit-button" data-post-id="{{ post.pk }}">작성</button>
    </form><br>
    {% if comments %}
        <ul class="list-group" id="comments-list-{{ post.pk }}" style="margin-top: 40px;">
            {% for comment in comments %}
	            {% include 'comments/_comment. html' with comment=comment user=user %}
	        {% endfor %}
        </ul>
    {% endif %}
        

    <span href="#" class="like" name ="{{post.id}}" value="Like"> 

        {% if user in post.like_user_set.all %}
            <div class="alt-service-icon">
                <i class="fas fa-thumbs-up" id ="like-icon" style="color:red;"></i>
             </div> 
        {% else %}
    
            <div class="alt-service-icon">
                 <i class="far fa-thumbs-up" id ="like-icon" style="color:red;"></i> 
            </div>
    
         {% endif %}
    
         <span id="count-{{ post.id }}" class="alt-services-title font-alt"> 
            좋아요 
            {% if post.like_count == 0 %} 
                0개 
            {% else %}
                {{ post.like_count }}개
            {% endif %}
         </span>
    </span>
    <span href="#" class="dislike" name ="{{post.id}}" value="Dislike"> 

        {% if user in post.dislike_user_set.all %}
            <div class="alt-service-icon">
                <i class="fas fa-thumbs-down" id ="dislike-icon" style="color:black;"></i>
             </div> 
        {% else %}
    
            <div class="alt-service-icon">
                 <i class="far fa-thumbs-down" id ="dislike-icon" style="color:black;"></i> 
            </div>
    
         {% endif %}
    
         <span id="count1-{{ post.id }}" class="alt-services-title font-alt"> 
            싫어요 
            {% if post.dislike_count == 0 %} 
                0개 
            {% else %}
                {{ post.dislike_count }}개
            {% endif %}
         </span>
    </span>

</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>
    $(".like").click(function(){
        var pk = $(this).attr('name')
        $.ajax({

            type:"POST",
            url : "{% url 'items:like_toggle' post.pk %}",
            data : {'pk':pk,'csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType:"json",

            success: function(response){

                if (response.like_count==null){
                    alert("로그인이 필요합니다.");
                    window.location.replace('/accounts/login/')
                }
                else{
                    if (response.result == "like"){
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('fas fa-thumbs-up');
                    }
                    else{
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('far fa-thumbs-up');
                    }

                    $('#count-{{ post.id }}').html('좋아요 '+response.like_count+'개');
                }
            },

            error: function(request, status, error){
                alert("로그인이 필요합니다.") // +"\n"+"error:"+error) 
	            // window.location.replace("/accounts/login/") 
	            alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error); 
        	},
         });
    })

    $(".dislike").click(function(){
        var pk = $(this).attr('name')
        $.ajax({
            type:"POST",
            url : "{% url 'items:dislike_toggle' post.pk %}",
            data : {'pk':pk,'csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType:"json",

            success: function(response){

                if (response.dislike_count==null){
                    alert("로그인이 필요합니다.");
                    window.location.replace('/accounts/login/')
                }
                else{
                    if (response.result == "dislike"){
                        $('#dislike-icon').removeClass();
                        $('#dislike-icon').addClass('fas fa-thumbs-down');
                    }
                    else{
                        $('#dislike-icon').removeClass();
                        $('#dislike-icon').addClass('far fa-thumbs-down');
                    }

                    $('#count1-{{ post.id }}').html('싫어요 '+response.dislike_count+'개');
                }
            },
        });
    })
    $('.comment-submit-button').click(function(e){
        e.preventDefault();
        const postId = $(this).data('post-id');
        const commentMessage = $(`#comment-input-${postId}`).val();
        console.log(commentMessage)
        if (commentMessage === '') {
            alert('댓글 내용을 입력해주세요.');
        } else {
            $.ajax({
                url: "{% url 'items:create_comment' post.pk %}",
                type: "POST",
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'content': commentMessage
                },
                success: function(response) {
                    $(`#comments-list-${postId}`).prepend(response.comment);
                    $(`#comment-input-${postId}`).val('');
                },
                error: function(response) {
                    alert('오류가 발생했습니다.');
                }
            });
        }
    });

 </script>
    
{% endblock %}

items/templates/items/home.html
{% extends 'base.html' %}
{% load static %}
<!-- 
{% block css %}
    <link rel="stylesheet" href="{% static 'css/item_list.css' %}">
{% endblock css %} -->

{% block content %}
    <div class="container">
        <div class="row">
            {% for item in items %}
                <div class="col-md-3 col-6 item_list__card">
                    <div class="card">
                        {% if item.image %}
                            <a href="#">
                                <img src="{{ item.image.url }}" width="100%" height="300px" alt="...">
                            </a>
                            <div class="card-body">
                                <h5 class="card-title">{{ item.title }}</h5>
                                <a href="{% url 'items:show' item.pk %}" class="btn btn-outline-primary">보러가기</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

items/templates/items/new.html
  
{% extends 'base.html'%}

{% block content %}
<div class="container">
        <form action="{% url 'items:create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <h1> 글 쓰기 </h1>
                <label>글 제목</label>
                <input type="text" class="form-control" name="title">
                </div>
                <div class="form-group">
                <label>글 내용</label>
                <textarea class="form-control" name="content"></textarea>
                <br>
                <input type="file" name="image">
            </div>
            <input type="submit" value="글 작성" class="btn btn-outline-primary">
        </form> 
</div>
{% endblock %}

items/templates/items/show.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1><상세보기 페이지></h1>
    <br>
    <h3>글 제목 : {{ post.title }} </h3><br>
    <h3>글 내용 : {{ post.content }} </h3><br>
    <h3>작성 시각 : {{ post.created_at }} </h3><br>
    <h4>조회 수: {{ post.view_count }} </h4><br>

    {% if post.user %}
        <h3> 작성자 : {{ post.user }}</h3>
    {% else %}
        <h3> 작성자 : 알수 없음</h3>
    {% endif %}

    {% if post.image %}
        <img src="{{ post.image.url }}" width="500px" height="500px">
    {% endif %}
    <br>

    {% if post.user == user %}
        <a href="{% url 'items:delete' post.pk %}"> 삭제하기 </a>
    {% endif %}

    <form action="#" method="POST" style="margin-top: 50px;" class="create-comment-form">
        {% csrf_token %}
        <div class="form-group">
            <textarea class="form-control" name="content" id="comment-input-{{ post.pk }}" placeholder="댓글 작성..."></textarea>
        </div>
        <button type="submit" class="btn btn-primary comment-submit-button" data-post-id="{{ post.pk }}">작성</button>
    </form><br>
    {% if comments %}
        <ul class="list-group" id="comments-list-{{ post.pk }}" style="margin-top: 40px;">
            {% for comment in comments %}
	            {% include 'comments/_comment.html' with comment=comment user=user %}
	        {% endfor %}
        </ul>
    {% endif %}
        

    <span href="#" class="like" name ="{{post.id}}" value="Like"> 

        {% if user in post.like_user_set.all %}
            <div class="alt-service-icon">
                <i class="fas fa-thumbs-up" id ="like-icon" style="color:red;"></i>
             </div> 
        {% else %}
    
            <div class="alt-service-icon">
                 <i class="far fa-thumbs-up" id ="like-icon" style="color:red;"></i> 
            </div>
    
         {% endif %}
    
         <span id="count-{{ post.id }}" class="alt-services-title font-alt"> 
            좋아요 
            {% if post.like_count == 0 %} 
                0개 
            {% else %}
                {{ post.like_count }}개
            {% endif %}
         </span>
    </span>
    <span href="#" class="dislike" name ="{{post.id}}" value="Dislike"> 

        {% if user in post.dislike_user_set.all %}
            <div class="alt-service-icon">
                <i class="fas fa-thumbs-down" id ="dislike-icon" style="color:black;"></i>
             </div> 
        {% else %}
    
            <div class="alt-service-icon">
                 <i class="far fa-thumbs-down" id ="dislike-icon" style="color:black;"></i> 
            </div>
    
         {% endif %}
    
         <span id="count1-{{ post.id }}" class="alt-services-title font-alt"> 
            싫어요 
            {% if post.dislike_count == 0 %} 
                0개 
            {% else %}
                {{ post.dislike_count }}개
            {% endif %}
         </span>
    </span>

</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>
    $(".like").click(function(){
        var pk = $(this).attr('name')
        $.ajax({

            type:"POST",
            url : "{% url 'items:like_toggle' post.pk %}",
            data : {'pk':pk,'csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType:"json",

            success: function(response){

                if (response.like_count==null){
                    alert("로그인이 필요합니다.");
                    window.location.replace('/accounts/login/')
                }
                else{
                    if (response.result == "like"){
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('fas fa-thumbs-up');
                    }
                    else{
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('far fa-thumbs-up');
                    }

                    $('#count-{{ post.id }}').html('좋아요 '+response.like_count+'개');
                }
            },

            error: function(request, status, error){
                alert("로그인이 필요합니다.") // +"\n"+"error:"+error) 
	            // window.location.replace("/accounts/login/") 
	            alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error); 
        	},
         });
    })

    $(".dislike").click(function(){
        var pk = $(this).attr('name')
        $.ajax({
            type:"POST",
            url : "{% url 'items:dislike_toggle' post.pk %}",
            data : {'pk':pk,'csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType:"json",

            success: function(response){

                if (response.dislike_count==null){
                    alert("로그인이 필요합니다.");
                    window.location.replace('/accounts/login/')
                }
                else{
                    if (response.result == "dislike"){
                        $('#dislike-icon').removeClass();
                        $('#dislike-icon').addClass('fas fa-thumbs-down');
                    }
                    else{
                        $('#dislike-icon').removeClass();
                        $('#dislike-icon').addClass('far fa-thumbs-down');
                    }

                    $('#count1-{{ post.id }}').html('싫어요 '+response.dislike_count+'개');
                }
            },
        });
    })
    
    $('.comment-submit-button').click(function(e){
        e.preventDefault();
        const postId = $(this).data('post-id');
        const commentMessage = $(`#comment-input-${postId}`).val();
        console.log(commentMessage)
        if (commentMessage === '') {
            alert('댓글 내용을 입력해주세요.');
        } else {
            $.ajax({
                url: "{% url 'items:create_comment' post.pk %}",
                type: "POST",
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'content': commentMessage
                },
                success: function(response) {
                    $(`#comments-list-${postId}`).prepend(response.comment);
                    $(`#comment-input-${postId}`).val('');
                },
                error: function(response) {
                    alert('오류가 발생했습니다.');
                }
            });
        }
    });

    $('.comment-delete-button').click(function(e){
        e.preventDefault();
        const deleteCommentButton = $(this);
        const commentId = $(this).data('comment-id');
            $.ajax({
                url: `../../delete_comment/${commentId}/`,
                type: "POST",
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                success: function(response) {
                    $(`#comment-${commentId}`).remove();
                },
                error: function(response) {
                    alert('오류가 발생했습니다.');
                }
            });
    });

 </script>
    
{% endblock %}